Index based
matt-frey/epic pull request #286
Opened 2022-01-17 18:19 UTC by sjboeing

Hi @matt-frey. Here is the work that stores the contributions to the grid in case support points correspond to the same index. Let me know if you can check it for the issue you spotted before.

2022-01-17 18:24 UTC, sjboeing commented
My changes to the moist setup are based on this one, so would be best to merge this one first if all is OK.

2022-01-17 18:34 UTC, sjboeing commented
One thing that originally did not work was OpenMP (I had to fix line length).

2022-01-18 08:54 UTC, matt-frey commented
I ran with OpenMP. Yes, I remember a line length issue.

2022-01-18 14:12 UTC, matt-frey commented
@sjboeing Have you tested that you still get the same results?

2022-01-18 18:46 UTC, matt-frey requested changes
I have two remarks.

2022-01-18 18:46 UTC, matt-frey commented on src/3d/parcels/parcel_interpl.f90
> +        pure subroutine trilinear_weights_inner(xyz, i_lower, j_lower, k_lower, ww)
Can we maybe rename this to `get_weights` or similar? I would also change `i_lower` etc. to just `i`.

2022-01-18 18:46 UTC, matt-frey commented on src/3d/parcels/parcel_interpl.f90
> +            ww(1) = ww(1)+pzc * w00
Please add spaces before and after `+`. Thanks.

2022-01-18 21:55 UTC, sjboeing commented
Just revised the subroutines. Let me know if it is ready to merge.

2022-01-18 22:00 UTC, sjboeing commented on src/3d/parcels/parcel_interpl.f90
> +        pure subroutine trilinear_weights_inner(xyz, i_lower, j_lower, k_lower, ww)
Changed it to get_weights, which is indeed more explicit, with indices i, j, k (also used this naming in trilinear_weights_add now).

2022-01-18 22:00 UTC, sjboeing commented on src/3d/parcels/parcel_interpl.f90
> +            ww(1) = ww(1)+pzc * w00
Done this.

2022-01-19 08:58 UTC, matt-frey commented on src/3d/parcels/parcel_interpl.f90
> +            ww(1) = ww(1)+pzc * w00
Thanks!

2022-01-19 09:04 UTC, matt-frey approved these changes
@sjboeing I fixed a few more white spaces (with https://github.com/matt-frey/epic/pull/286/commits/6f8c49e8c189d6423ca6606eda181a7e65115e07). Thanks a lot for working on this!

2022-01-19 09:26 UTC, merged